src/GEL/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from .views import (
    home,
    about,
    contact,
    send_email,
    founder_info,
)

from marketing.views import subscribe_email

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('', home, name='home'),
    path('about/', about, name='about'),
    path('contact/', contact, name='contact'),
    path('founder_info/', founder_info, name='founder_info'),
    path('send_email', send_email, name='send_email'),
    path('post/', include('post.urls')),
    path('gallery/', include('gallery.urls')),
    path('subscribe/', include('marketing.urls')),
]

if settings.DEBUG:
    urlpatterns = urlpatterns + \
        static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + \
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/gallery/urls.py
from django.urls import path

from .views import *

app_name = 'gallery'

urlpatterns = [
    path('', gallery, name='gallery'),
    path('picture_gallery/', picture_gallery, name='picture_gallery'),
    path('video_gallery/', video_gallery, name='video_gallery'),
]

src/post/urls.py
from django.urls import path

from .views import *

app_name = 'post'

urlpatterns = [
    path('', post, name='post'),
    path('<int:id>/<slug:slug>/', post_detail, name='post_detail'),
    path('search/', post_search, name='post_search'),
    path('search_tag/<slug:tag>/', post_tag_search, name='post_tag_search'),
]

src/templates/about.html
{% extends 'main.html' %}

{% load static %}

{% block content %}

<!--Breadcrumb Banner Area Start-->
<div class="breadcrumb-banner-area">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="breadcrumb-text">
                    <h1 class="text-center">ABOUT US</h1>
                    <div class="breadcrumb-bar">
                        <ul class="breadcrumb text-center">
                            <li><a href="{% url 'home' %}">Home</a></li>
                            <li>ABOUT US</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!--End of Breadcrumb Banner Area-->

<!--About Page Area Start-->
<div class="about-page-area section-padding">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="section-title-wrapper">
                    <div class="section-title">
                        <h3>Who we are</h3>
                        <p>Education is the most powerful weapon we use to change the world.</p>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                <div class="about-text-container">
                    <p><span>Well come to Green Edu Link</span> come with us, we also teach children about the basic values of human beings as honesty, kindness, generosity, courage, freedom, equality and respect. Learn to celebrate diversity in a spirit of understanding and tolerance and develop a positive regard and awareness of other people. They are taught the values and responsibilities needed to become active members of the community, tolerance and develop something which the modern world is desperate for norem ipsum dolor sit amet desperate.</p>
                    <div class="about-us">
                        <span>Nam gravida magna vitae ante dignissim</span>
                        <span>Duis rhoncus lectus at velit hendrerit quis</span>
                        <span>Sed fringilla tempor arcu feugiat risus</span>
                        <span>Vivamus semper odio in nibh ultricies</span>
                    </div>    
                    <p>Snos trud exerci tation ullorper suscipit lobo maeisrn roester maeoirqs iserrtis nisl ut aliq poerwse thesr oper balinp asein hoinws mawsoib equat. Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more tolerance and develop obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through makin of the word in classical literature.</p>
                </div>
            </div>
            <div class="col-md-6">
                <div class="skill-image">
                    <img src="{% static 'img/logo/about_us_2.jpg' %}" alt="">
                </div>
            </div>
        </div>
    </div>
</div>
<!--End of About Page Area-->

<!--Teachers Area Start-->
<div class="teachers-area padding-top">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="section-title-wrapper">
                    <div class="section-title">
                        <h3>OUR FOUNDER</h3>
                        <p>A good teacher is like a candle – it consumes itself to light the way for others - Mustafakemal Ataturk</p>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-3 col-md-4 col-sm-6" style="float: none; margin: 0 auto;">
                <div class="single-teacher-item">
                    <div class="single-teacher-image">
                        <a href="{% url 'founder_info' %}"><img src="{% static 'img/teacher/anthonynguyen2.jpg' %}" alt=""></a>
                    </div>
                    <div class="single-teacher-text">
                        <h3><a href="{% url 'founder_info' %}">Anthony Nguyen</a></h3>
                        <h4>CEO</h4>
                        <p>"Engineering is the closest thing to magic that exists in the world."</p>
                        <p>Elon Musk</p>
                        <div class="social-links">
                            <a href="https://www.facebook.com/dung.tri.102" target="_blank"><i class="zmdi zmdi-facebook"></i></a>
                            <a href="#"><i class="zmdi zmdi-twitter"></i></a>
                            <a href="#"><i class="zmdi zmdi-google-old"></i></a>
                            <a href="#"><i class="zmdi zmdi-instagram"></i></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!--End of Teachers Area-->

{% endblock content %}

src/templates/contact.html
{% extends 'main.html' %}

{% load static %}

{% block content %}

<!--Breadcrumb Banner Area Start-->
<div class="breadcrumb-banner-area">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="breadcrumb-text">
                    <h1 class="text-center">CONTACT US</h1>
                    <div class="breadcrumb-bar">
                        <ul class="breadcrumb text-center">
                            <li><a href="{% url 'home' %}">Home</a></li>
                            <li>CONTACT</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!--End of Breadcrumb Banner Area-->

{% if not success_msg and not error_msg %}
<!--Google Map Area Start-->
<div class="google-map-area">
    <!--  Map Section -->
    <div id="contacts" class="map-area">
        <div id="googleMap" style="width:100%;height:700px">
            <iframe style="width:100%; height:100%;" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d1647.8669018681649!2d106.6847548276217!3d10.787545404848634!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x31752f2c5552702f%3A0xf0adaedb0d2fc89a!2sGalasoft%20Co.%2C%20Ltd!5e0!3m2!1sen!2s!4v1586305376641!5m2!1sen!2s" frameborder="0" allowfullscreen="" aria-hidden="false" tabindex="0"></iframe>
        </div>
    </div>
</div>
<!--End of Google Map Area-->
{% endif %}

<!--Contact Form Area Start-->
<div class="contact-form-area section-padding">
    <div class="container">
        <div class="row">
            <div class="col-md-4">
                <h4 class="contact-title">contact info</h4>
                <div class="contact-text">
                    <p><span class="c-icon"><i class="zmdi zmdi-phone"></i></span><span class="c-text">(+84) 982 205 216 - (+84) 937 691 089</span></p>
                    <p><span class="c-icon"><i class="zmdi zmdi-email"></i></span><span class="c-text">info.greenedulink@gmail.com</span></p>
                    <p><span class="c-icon"><i class="zmdi zmdi-pin"></i></span><span class="c-text">M Floor, 117-119 Ly Chinh Thang Street,<br> Ward 7, District 3, Ho Chi Minh City</span></p>
                </div>
                <h4 class="contact-title">social media</h4>
                <div class="link-social">
                    <a href="https://www.facebook.com/greenedulink" target="_blank"><i class="zmdi zmdi-facebook"></i></a>
                    <a href="#"><i class="zmdi zmdi-rss"></i></a>
                    <a href="#"><i class="zmdi zmdi-google-plus"></i></a>
                    <a href="#"><i class="zmdi zmdi-pinterest"></i></a>
                    <a href="#"><i class="zmdi zmdi-instagram"></i></a>
                </div>
            </div>
            <div class="col-md-7">
                <h4 class="contact-title">send your massage</h4>
                <form action="{% url 'send_email' %}" method="post">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-md-6">
                            <input type="text" name="name" placeholder="name">
                        </div>
                        <div class="col-md-6">
                            <input type="email" name="email" placeholder="Email">
                        </div>
                        <div class="col-md-12">
                            <textarea name="message" cols="30" rows="10" placeholder="Message"></textarea>
                            <button type="submit" class="button-default">SUBMIT</button>
                        </div>
                    </div>
                </form>

                {% if success_msg %}
                <div class="alert alert-success" role="alert">
                    {{ success_msg }}
                </div>
                {% elif error_msg %}
                <div class="alert alert-danger" role="alert">
                    {{ error_msg }}
                </div>
                {% endif %}

            </div>
        </div>
    </div>
</div>
<!--End of Contact Form-->

{% endblock content %}

src/templates/header.html
{% load static %}

<!--Header Area Start-->
<header>
    <div class="header-top">
        <div class="container">
            <div class="row">
                <div class="col-lg-7 col-md-6 col-sm-6 hidden-xs">
                    <span>Have any question? (+84) 982 205 216</span>
                </div>
                <div class="col-lg-5 col-md-6 col-sm-6 col-xs-12">
                    <div class="header-top-right" style="width:600px; margin-right:-200px">
                        <div class="content"><a href="https://www.facebook.com/greenedulink" target="_blank"><i class="zmdi zmdi-facebook"></i> Facebook</a></div>
                        <div class="content"><a href="https://www.facebook.com/greenedulink/about/?ref=page_internal" target="_blank"><i class="zmdi zmdi-email"></i> Gmail</a></div>
                        <div class="content"><a href="#" target="_blank"><i class="zmdi zmdi-youtube"></i> Youtube</a></div>
                        <div class="content"><a href="#" target="_blank"><i class="zmdi zmdi-twitter"></i> Twitter</a></div>
                        <div class="content"><a href="#" target="_blank"><i class="zmdi zmdi-pinterest"></i> Pinterest</a></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="header-logo-menu sticker">
        <div class="container">
            <div class="row">
                <div class="col-md-3 col-sm-12">
                    <div class="logo" style="width: 400px">
                        <a href="{% url 'home' %}"><img src="{% static 'img/logo/logo2.png' %}" alt="GREEN EDU LINK" style="margin-top:-50px"></a>
                        <div style="display: inline-block; margin-left: 10px; border:1px solid red">
                            <h2>Green Edu Link</h2>
                            <h4>Connect to success</h4>
                        </div>
                    </div>
                </div>
                <div class="col-md-9 hidden-sm hidden-xs">
                    <div class="mainmenu-area pull-right">
                        <div class="mainmenu">
                            <nav>
                                <ul id="nav">
                                    <li class="current"><a href="{% url 'home' %}">Home</a></li>
                                    <li><a href="{% url 'post:post' %}">News</a></li>
                                    <li><a href="#">Schoolarships</a></li>
                                    <li><a href="{% url 'gallery:gallery' %}">Galleries</a>
                                        <ul class="sub-menu">
                                            <li><a href="{% url 'gallery:picture_gallery' %}">Pictures</a></li>
                                            <li><a href="{% url 'gallery:video_gallery' %}">Videos</a></li>
                                        </ul>
                                    </li>
                                    <li><a href="{% url 'about' %}">About</a></li>
                                    <li><a href="{% url 'contact' %}">Contact</a></li>
                                </ul>
                            </nav>
                        </div>
                        <ul class="header-search">
                            <li class="search-menu">
                                <i id="toggle-search" class="zmdi zmdi-search"></i>
                            </li>
                        </ul>
                        <!--Search Form-->
                        <div class="search">
                            <div class="search-form">
                                <form id="search-form" action="{% url 'post:post_search' %}" method="get">
                                    <input type="search" placeholder="Search here..." name="search_query" />
                                    <button type="submit">
                                        <span><i class="fa fa-search"></i></span>
                                    </button>
                                </form>
                            </div>
                        </div>
                        <!--End of Search Form-->
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Mobile Menu Area start -->
    <div class="mobile-menu-area">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12">
                    <div class="mobile-menu">
                        <nav id="dropdown">
                            <ul>
                                <li class="current"><a href="{% url 'home' %}">Home</a></li>
                                <li><a href="{% url 'post:post' %}">News</a></li>
                                <li><a href="#">Schoolarships</a></li>
                                <li><a href="shop-grid.html">Galleries</a>
                                    <ul class="sub-menu">
                                        <li><a href="{% url 'gallery:picture_gallery' %}">Pictures</a></li>
                                        <li><a href="{% url 'gallery:video_gallery' %}">Videos</a></li>
                                    </ul>
                                </li>
                                <li><a href="{% url 'about' %}">About</a></li>
                                <li><a href="{% url 'contact' %}">Contact</a></li>
                            </ul>
                        </nav>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Mobile Menu Area end -->
</header>
<!--End of Header Area-->

src/templates/home.html
{% extends "main.html" %}

{% load static %}

{% block content %}

<!--Slider Area Start-->
<div class="slider-area">
    <div class="preview-2">
        <div id="nivoslider" class="slides">
            <img src="{% static 'img/banner/home_banner.png' %}" alt="" title="#slider-1-caption1" style="width:1920px;height:800px;"/>
            <img src="{% static 'img/banner/home_banner_2.png' %}" alt="" title="#slider-1-caption2" style="width:1920px;height:800px;"/>
        </div>
        <div id="slider-1-caption1" class="nivo-html-caption nivo-caption">
            <div class="banner-content slider-1">
                <div class="container">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="text-content-wrapper">
                                <div class="text-content">
                                    <h1 class="title1 wow fadeInUp" data-wow-duration="2000ms" data-wow-delay="0s">
                                        Education Needs<br>
                                        Complete Solution</h1>
                                    <p class="sub-title wow fadeInUp hidden-sm hidden-xs" data-wow-duration="2900ms"
                                        data-wow-delay=".5s"> There are many variations of passages of Lorem Ipsum
                                        available, but the majority have<br>
                                        suffered alteration in some form, by injected humour, or randomised words
                                        which<br>
                                        don't look even slightly believable.</p>
                                    <div class="banner-readmore wow fadeInUp" data-wow-duration="3600ms"
                                        data-wow-delay=".6s">
                                        <a class="button-default" href="#">View Courses</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div id="slider-1-caption2" class="nivo-html-caption nivo-caption">
            <div class="banner-content slider-2">
                <div class="container">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="text-content-wrapper">
                                <div class="text-content slide-2">
                                    <h1 class="title1 wow rotateInDownLeft" data-wow-duration="1000ms"
                                        data-wow-delay="0s">Education Needs<br>
                                        Complete Solution</h1>
                                    <p class="sub-title wow rotateInDownLeft hidden-sm hidden-xs"
                                        data-wow-duration="1800ms" data-wow-delay="0s"> There are many variations of
                                        passages of Lorem Ipsum available, but the majority have<br>
                                        suffered alteration in some form, by injected humour, or randomised words
                                        which<br>
                                        don't look even slightly believable.</p>
                                    <div class="banner-readmore wow rotateInDownLeft" data-wow-duration="1800ms"
                                        data-wow-delay="0s">
                                        <a class="button-default" href="#">View Courses</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!--End of Slider Area-->

<!--About Area Start-->
<div class="about-area">
    <div class="container">
        <div class="row">
            <div class="col-md-8">
                <div class="about-container"style="height:400px">
                    <h3>WHY GREEN EDU LINK?</h3>
                    <p style="font-weight: bold; font-size:15px">
                        “If You are planning for a year, sow rice; if you are planning for a decade, plant trees; if you are planning for a lifetime, educate people”
                    </p>
                    <p style="color:black; font-size:25px; font-weight: bold">Chinese Proverb</p>
                    <a class="button-default" href="#">Learn Now</a>
                </div>
            </div>
        </div>
    </div>
</div>
<!--End of About Area-->

<!--Course Area Start-->
<div class="course-area section-padding bg-white">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="section-title-wrapper">
                    <div class="section-title">
                        <h3>POPULAR UNIVERSITIES</h3>
                        <p>“Education is the most powerful weapon which you can use to change the world” – Nelson Mandela</p>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">

        {% for post in university_posts %}

            <div class="col-md-4 col-sm-6">
                <div class="single-item">
                    <div class="single-item-image overlay-effect">
                        <a href="{{ post.post_id.get_absolute_url }}"><img src="{{ post.post_id.thumbnail.url }}" alt=""></a>
                    </div>
                    <div class="single-item-text">
                        <h4><a href="{{ post.post_id.get_absolute_url }}">{{ post.post_id.title }}</a></h4>
                        <div class="single-item-text-info">
                            <span>By: <span>{{ post.post_id.user_id.get_full_name }}</span></span>
                            <span>Date: <span>{{ post.post_id.created_at }}</span></span>
                        </div>
                        <p>{{ post.description }}</p>
                        <div class="single-item-content">
                            <div class="single-item-comment-view">
                                <span><i class="zmdi zmdi-eye"></i>{{ post.post_id.views }}</span>
                                <span><i class="zmdi zmdi-comments"></i>{{ post.post_id.comments }}</span>
                            </div>
                            <div class="single-item-rating">
                                <i class="zmdi zmdi-star"></i>
                                <i class="zmdi zmdi-star"></i>
                                <i class="zmdi zmdi-star"></i>
                                <i class="zmdi zmdi-star"></i>
                                <i class="zmdi zmdi-star-half"></i>
                            </div>
                        </div>
                    </div>
                    <div class="button-bottom">
                        <a href="{{ post.post_id.get_absolute_url }}" class="button-default">Learn Now</a>
                    </div>
                </div>
            </div>

        {% endfor %}

            <div class="col-md-12 col-sm-12 text-center">
                <a href="{% url 'post:post' %}" class="button-default button-large">Browse All Posts <i
                        class="zmdi zmdi-chevron-right"></i></a>
            </div>
        </div>
    </div>
</div>
<!--End of Course Area-->

<!--Fun Factor Area Start-->
<div class="fun-factor-area">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="section-title-wrapper white">
                    <div class="section-title">
                        <h3>IMPORTANT FACTS</h3>
                        <p>There are many variations of passages of Lorem Ipsum</p>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-3 col-sm-3">
                <div class="single-fun-factor">
                    <h4>Teachers</h4>
                    <h2><span class="counter">79</span>+</h2>
                </div>
            </div>
            <div class="col-md-3 col-sm-3">
                <div class="single-fun-factor">
                    <h4>Members</h4>
                    <h2><span class="counter">120</span>+</h2>
                </div>
            </div>
            <div class="col-md-3 col-sm-3">
                <div class="single-fun-factor">
                    <h4>Courses</h4>
                    <h2><span class="counter">36</span>+</h2>
                </div>
            </div>
            <div class="col-md-3 col-sm-3">
                <div class="single-fun-factor">
                    <h4>Countries</h4>
                    <h2><span class="counter">20</span>+</h2>
                </div>
            </div>
        </div>
    </div>
</div>
<!--End of Fun Factor Area-->

<!--Latest News Area Start-->
<div class="latest-area section-padding bg-white">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="section-title-wrapper">
                    <div class="section-title">
                        <h3>Latest News</h3>
                        <p>Learning is the eye of the mind.</p>
                    </div>
                </div>
            </div>
        </div>

        <div class="row">

                {% for post in posts %}

                    <div class="col-md-6">
                        <div class="single-latest-item">
                            <div class="single-latest-image">
                                <a href="{{ post.get_absolute_url }}"><img src="{{ post.thumbnail.url }}" alt="" style="width:250px;height:230px;"></a>
                            </div>
                            <div class="single-latest-text" style="height:230px">
                                <h3 style="height:60px"><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h3>
                                <div class="single-item-comment-view">
                                    <span><i class="zmdi zmdi-calendar-check"></i>{{ post.created_at }}</span>
                                    <span><i class="zmdi zmdi-eye"></i>{{ post.views }}</span>
                                    <span><i class="zmdi zmdi-comments"></i>{{ post.comments }}</span>
                                </div>
                                <p>{{ post.description }}</p>
                                <a href="{{ post.get_absolute_url }}" class="button-default">READ NOW</a>
                            </div>
                        </div>
                    </div>
            
            {% endfor %}
            
        </div>
    </div>
</div>
<!--End of Latest News Area-->

<!--Teachers Area Start-->
<div class="teachers-area padding-top">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="section-title-wrapper">
                    <div class="section-title">
                        <h3>OUR FOUNDERS</h3>
                        <p>A good teacher is like a candle – it consumes itself to light the way for others - Mustafakemal Ataturk</p>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-3 col-md-4 col-sm-6" style="float: none; margin: 0 auto;">
                <div class="single-teacher-item">
                    <div class="single-teacher-image">
                        <a href="{% url 'founder_info' %}"><img src="{% static 'img/teacher/anthonynguyen2.jpg' %}" alt=""></a>
                    </div>
                    <div class="single-teacher-text">
                        <h3><a href="{% url 'founder_info' %}">Anthony Nguyen</a></h3>
                        <h4>CEO</h4>
                        <p>"Engineering is the closest thing to magic that exists in the world."</p>
                        <p>Elon Musk</p>
                        <div class="social-links">
                            <a href="https://www.facebook.com/dung.tri.102" target="_blank"><i class="zmdi zmdi-facebook"></i></a>
                            <a href="#"><i class="zmdi zmdi-twitter"></i></a>
                            <a href="#"><i class="zmdi zmdi-google-old"></i></a>
                            <a href="#"><i class="zmdi zmdi-instagram"></i></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!--End of Teachers Area-->

{% endblock content %}

src/templates/main.html
{% load static %}

<!doctype html>
<html class="no-js" lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Green Edu Link</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- css section
		============================================ -->
    {% include 'css.html' %}

</head>

<body>
    <!--[if lt IE 8]>
            <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->

    <!--Main Wrapper Start-->
    <div class="as-mainwrapper">

        <!--Bg White Start-->
        <div class="bg-white">

            <!--Header Area Start-->
            {% include 'header.html' %}
            <!--End of Header Area-->

            {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}" {% endif %}>
                    {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Important: {% endif %}
                    {{ message }}
                    </li>
                    {% endfor %}
            </ul>
            {% endif %}

            <!--Body Area Start-->
            {% block content %}{% endblock %}
            <!--End of Body Area-->

            <!--Footer Area Start-->
            {% include 'footer.html' %}
            <!--End of Footer Area-->

        </div>
        <!--End of Bg White-->

    </div>
    <!--End of Main Wrapper Area-->

    <!-- js section
		============================================ -->
    {% include 'js.html' %}

</body>

</html>